DROP TABLE IF EXISTS sensors;
 
CREATE TABLE sensors (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sensor_name VARCHAR(255) NOT NULL,
  sensor_file VARCHAR(255) NOT NULL,
  sensor_class VARCHAR(255) NOT NULL
);